services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - EXTERNAL_PORT=${EXTERNAL_PORT}
            - PORT=${PORT}
            - CORS_ORIGINS=*
            - IFRAME_ORIGINS=*
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
        # env_file:
        #     - .env
        ports:
            - '${EXTERNAL_PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
